#!/bin/bash
set -eo pipefail


# Allow sharing of perforce client workspaces for the same stream between pipelines
if [[ "${BUILDKITE_PLUGIN_PERFORCE_SHARE_WORKSPACE}" != "no" ]]; then
  echo "Workspace sharing enabled"

  STREAM="${BUILDKITE_BRANCH}"
  if [[ -z "${STREAM}" ]]; then
    echo "Error: You must use stream workspaces to enable shared workspaces" >&2
    exit 1
  fi
  if [[ "${BUILDKITE_AGENT_META_DATA_AGENT_COUNT}" -gt 1 ]]; then
    echo "Error: You cannot share stream workspaces when running more than one agent" >&2
    exit 1
  fi
  # Sanitize '//depot/stream-name' to '++depot+stream-name'
  SANITIZED_STREAM=$(echo $STREAM | python -c "import sys; print(sys.stdin.read().split('!')[0].replace('/', '+'));")
fi

if [ -n "${P4PASSWD}" ]; then
  echo "Logging into P4 early"
  p4 trust -y
  echo $P4PASSWD | p4 login
fi
